version: "3.9"

services:
  web3:
    build:
      context: .
    container_name: web3
    restart: always
    environment:
      DB_HOST: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: "5432:5432"
      POSTGRES_NAME: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres


  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"