version: "3.9"

services:
  ton_back:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    env_file: .env
    ports:
      - "8092:8090"
    depends_on:
      - ton_bd


  ton_bd:
    image: postgres:13.3
    restart: always
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres-data: